spring:
  application:
    name: zuul
  datasource:
    url: jdbc:mysql://localhost:3306/sept2
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80
security:
  pubKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC78ejlQVWKh5g9m9HGmENrrhVZoagkL1xdh8+eQgLeuI4Ted8TORzWKkPhNO4Vu+MxcvmQ1ziYmdpfCqqrXSGHWtU/oBfuIUiQlJgOBzQiaLZPTo0yXtjV3RNQlBuvGzXuXuPN8bVSTmf5UjNoc/j5iZ4RbS0oCHHqPv4GupqaOQIDAQAB
  priKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBALvx6OVBVYqHmD2b0caYQ2uuFVmhqCQvXF2Hz55CAt64jhN53xM5HNYqQ+E07hW74zFy+ZDXOJiZ2l8KqqtdIYda1T+gF+4hSJCUmA4HNCJotk9OjTJe2NXdE1CUG68bNe5e483xtVJOZ/lSM2hz+PmJnhFtLSgIceo+/ga6mpo5AgMBAAECgYEAkhzhmMmQPSBpZQwsrB5X2/D8vDAHTgpb3oLlD/31yTzlh5KpsIIoPv+gwgaqSc9GM31VNBt97nU95cGfKZY/p2qyJcfVb2btHlqvrYcwLam5Yc3xeIIcToRZTlN/jaZMf2aChO3Zen+BLasB0tMzP3MWp9ykBB2L/p6EDXV3rbkCQQDv7OX0DpQQpK73fUi7irzxj62ZgN2Cw5x47Iyn+8ESworC4n2yQ5ITzT9SJFkYA+/jm1CrBeocbnJyiMYq8al3AkEAyIl271vy7fpylSAdn1yjJahjObrKhCtozKcO8dVMt1BW5v3elLqN/RsRPsw25atTE0imRclhOfvUcD6QtwbFzwJBAMl8W9zqhUO42Ur0BqmgqG4AaBx6UQvotDYFCVZlIM5dW+SwCjkzb7B7dErKRZvaapHtNAB79hAsXKZ84FbeHZ8CQGvsPwvWSkj0zhGfdRG8wziTBMOe2TqEOiRZi9tuVZkaLYqm+dDFDYE3vfIz6R91MoJgSMup8x9Hfi7iHPPDO1UCQQCst/6mbbC3OmxcsrOqOz0qEAcCiyoX1e86eaXaNLEOalPtyNMZVqMhdH6CqnYfUHURSi+v8L6M0roSjva2UgRJ
